### [C]reate dishes
POST http://localhost:3000/dishes
Content-Type: application/json

{
  "name": "Burgir",
  "servings": 1
}

### [R]ead dishes
GET http://localhost:3000/dishes

### [R]ead one dishe
GET http://localhost:3000/dishes/2

### [U]pdate dish
PUT http://localhost:3000/dishes
Content-Type: application/json

{
  "id": 1,
  "name": "Tacos",
  "servings": 3
}

### [D]elete dish
DELETE http://localhost:3000/dishes/1